# Generated by Django 5.2.7 on 2025-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='Ukraine', max_length=100),
            preserve_default=False,
        ),
    ]
